

scenes = {"Village": [
    ["> ", "My prized ship is gone. Its loyal crew, dead."],
    ["  ", "I thought myself the only survivor until I found that witch collapsed on the sand."],
    ["  ", "She must have dragged herself up from the surf before succumbing to exhaustion."],
    ["  ", "I nearly threw her back in. I've shared enough of her misfortune already."],
    ["  ", "I stayed my hand only because she fought with me."],
    ["  ", "I don't know why our goddess hates her, but it's not for cowardice."],
    ["  ", "..."],
    ["  ", "At any rate, my lion survived also. She found us while I was building a fire from driftwood."],
    ["  ", "I'm glad to have at least one true ally left."],
    ["  ", "Tomorrow, we'll head uphill towards a village I spotted to the north. Someone there might sell me a boat."],
    ["  ", "The witch can come along if she wakes by then."]
], "Post Village": [
    ["> ", "So much for the village."],
    ["  ", "The town itself is rotted; none of their rowboats look salvageable."],
    ["  ", "The only thing we gained in coming here was our new companion."],
    ["  ", "..."],
    ["> ", "As for the paladin, he claims he got stranded here after our own fashion."],
    ["  ", "His encounter with the sea snake occurred about a week prior. We're the first living people he's seen since."],
    ["  ", "He won't divulge details beyond that, which suits me fine."],
    ["  ", "Whatever business brought him here, I want no further part."],
    ["  ", "..."],
    ["> ", "We're all stuck together for the moment, unfortunately."],
    ["  ", "Akeem says there's a walled town atop the cliffs to the northwest."],
    ["  ", "We'll go there next, and since we can't sail, we'll climb through the caves."],
    ["  ", "The witch should feel at home. I'll be glad to have her, too, even if she is cursed."]
], "Town": [
    ["  ", "The paladin seems capable enough, but I don't like how much he smiles."],
    ["  ", "Too much has gone awry for me to share another's mirth. I wish he'd stop trying to cheer us up."],
    ["  ", "Even Fadia seems annoyed. She won't complain though."],
    ["  ", "I don't think that woman has it in her to say anything cruel."],
    ["  ", "..."],
    ["  ", "I feel bad for snapping this morning. The shipwreck wasn't her fault. Even if she is cursed."],
    # ["  ", "Akeem thinks providence brought us together. I pray he's wrong."]
], "Post Town": [
    ["> ", "Another dead settlement. The temple at its heart was burned to ash."],
    ["  ", "We could see that from outside the mud-brick walls."],
    ["  ", "Akeem insisted on entering anyway, and Fadia wasn't willing to abandon him."],
    ["  ", "I went along because I'm dead either way, and I'd rather die with courage."],
    ["  ", "At least we got some answers at the end of it."],
    ["  ", "..."],
    ["> ", "There was a note staked to the chest of that headless paladin."],
    ["  ", "It simply reads, 'I warned you.'"],
    ["  ", "Akeem didn't look surprised to see that, which didn't shock me."],
    ["  ", "I nearly started shouting at him to get the truth, but Fadia just said,"],
    ["  ", " 'we deserve to know,' in that gentle voice of hers. It worked."],
    ["  ", "..."],
    ["> ", "It seems Akeem was the second member of his order sent to this nothing town."],
    ["  ", "The first, whom we just put down, was here chasing rumors of a vampire."],
    ["  ", "Seems to me he found one, but Akeem says even a powerful bloodsucker couldn't have blighted the land like this."],
    ["  ", "He's convinced something else is at work."],
    ["  ", "..."],
    ["  ", "His order's library had a dusty, crumbling map of this region."],
    ["  ", "Reading it, he learned of a western region called 'the Valley of Death.'"],
    ["  ", "We're going there next on the basis of its name. Joy."]
], "Valley": [
    ["> ", "The valley before us holds no structures aside from pyramids and hosts no life but scavengers."],
    ["  ", "This entire landscape is a massive, crumbling tomb."],
    ["  ", "The others almost seem excited to explore. I am the only sane one present."],
    ["  ", "..."],
    ["> ", "We climbed a small hill to survey what lies before us. At its peak, we found a weathered stele."],
    ["  ", "Several words had long since chipped away, but the most important phrase endured:"],
    ["  ", "'In this accursed valley is inturned a lich. Turn back before death claims you.'"],
    ["  ", "We know now what awaits us. I know not how we will vanquish it."],
    ["  ", "I cannot turn back alone."]
], "Lich": [
    ["> ", "We've reached the seat of this evil and will venture inside soon."],
    ["  ", "It appears humble from without- smaller and cruder than the pyramids around it."],
    ["  ", "From its scale and placement at the valley's end, we believe it to be older than its neighbors."],
    ["  ", "..."],
    ["> ", "Ancient glyphs mark its lintel, still legible after two thousand years of abandonment."],
    ["  ", "I had thought myself a learned man when I lived among sailors, but Akeem is a true scholar."],
    ["  ", "He managed to translate what remains of the inscription. Its words both sicken and encourage me."],
    ["  ", "..."],
    ["> ", "I had assumed the lich was never destroyed because his obliteration was impossible,"],
    ["  ", " but it seems he endures only because his captors wanted him to suffer."],
    ["  ", "He was an ancient lord whose peers hated him enough to make him an eternal prisoner."],
    ["  ", "Goddess willing, we will end his millennia of torment and stop the spread of his blight."],
    ["  ", "We can only hope his guards oblige us."]
], "Dragon": [
    ["> ", "We were fools to venture so deeply into this marsh."],
    ["  ", "In her benevolence, the goddess granted us what I suspect will be our only warning."],
    ["  ", "We saw and felt the dragon's shadow cross over our bodies before we heard the beating of its wings."],
    ["  ", "The great beast must have glided towards us silently, keeping to our blind spot until it rose from its dive."],
    ["  ", "..."],
    ["  ", "Fadia thinks the creature was merely curious. Akeem agreed with me that its coming was a message."],
    ["  ", "Both acknowledged that staying here would be the death of us. We're turning back."]
]}