

scenes = {"Leviathan": [
    ["> ", "A strange woman bought passage at our last port."],
    ["  ", "Dark-skinned, from south of the great desert, but speaks our language without accent."],
    ["  ", "She didn't care where we were going and seemed convinced I'd turn her away despite generous payment."],
    ["  ", "Wasn't at all bothered about being the only woman on board."],
    ["", ""],
    ["> ", "My crew immediately distrusted her. I don't trust her either, but coin is coin."],
    ["  ", "We don't even need to take her the full way- just drop her off at a small town along our route."],
    ["  ", "What's the worst that could happen?"]
], "Post Leviathan": [
    ["> ", "My prized ship is gone. Its loyal crew, lost and likely dead."],
    ["  ", "I thought myself the only survivor until I found that small witch collapsed on the sand."],
    ["  ", "She must have dragged herself up from the surf before succumbing to exhaustion."],
    ["", ""],
    ["> ", "I nearly threw her back in."],
    ["  ", "I've shared enough of this woman's misfortune already."],
    ["  ", "I only stayed my hand because she fought with me."],
    ["  ", "Whatever curse she carries, it was not earned through cowardice."],
    ["", ""],
    ["> ", "At any rate, my lion survived also."],
    ["  ", "Layth found us while I was building a fire from driftwood. Trotted up like nothing was wrong."],
    ["  ", "I'm glad to have at least one true ally left."]
], "Village": [
    ["> ", "Once the sun's fully risen, we'll head uphill towards a village I spotted to the north."],
    ["  ", "Someone there might sell me a rowboat."],
    ["  ", "The witch can come along if she regains consciousness by then."],
    ["  ", "..."],
    ["> ", "I put my pen down for a moment and tried shaking her awake. It worked."],
    ["  ", "After the woman got her bearings, I explained our predicament."],
    ["  ", "She took the news well, and she even has a plan."],
    ["", ""],
    ["> ", "There's a mountain about thirty miles south of here."],
    ["  ", "A man who lives there owes her family a favor."],
    ["  ", "She doesn't have much information about him beyond that, but she originally came here to seek his aid."],
    ["  ", "I didn't bother prying for details because we're not crossing that much water on our own."],
    ["  ", "That fishing village to the north is still our best hope for now."]
], "Post Village": [
    ["> ", "So much for the village."],
    ["  ", "The town itself is rotted; none of their rowboats look salvageable."],
    ["  ", "The only thing we gained in coming here was our new companion."],
    ["", ""],
    ["> ", "As for the paladin, he claims he got stranded here after our own fashion."],
    ["  ", "His encounter with the snake occurred about a week prior. We're the first living people he's seen since."],
    ["  ", "He won't divulge his purpose in coming here, which would suit me fine if not for us being stuck together."],
    ["  ", "Whatever business brought him, I want no further part."],
    ["  ", "I don't think I'm getting what I want."],
    ["", ""],
    ["> ", "Akeem confirmed that there's a walled town atop the cliffs to the northwest."],
    ["  ", "Fadia's original destination."],
    ["  ", "We'll go there next to see what's become of it. Since we can't sail, we'll have to climb through the caves."],
    ["  ", "The witch should feel at home. I'll be glad to have her, too, even if she is cursed."]
], "Town": [
    ["> ", "Another dead settlement. Its fate was obvious before this trek began, but now we have confirmation."],
    ["  ", "We circled around a bit before deciding what to do and found a break in the"],
    ["  ", "  outer wall that lines up with an alleyway leading into the main square."],
    ["  ", "From our current vantage, we can see both temples at the settlement's heart."],
    ["", ""],
    ["> ", "It seems that the people who lived here honored the northern god of fire next to our lady of light."],
    ["  ", "Since they're half-heretical and all-the-way dead, I suggested we should leave them to the fate they've already met."],
    ["  ", "Akeem insists on entering regardless, unfortunately, and Fadia isn't willing to abandon him."],
    ["  ", "I suppose I'm dead either way. I'd rather die with courage, so I'll go along."],
    ["", ""],
    ["> ", "Our one solace is that most of the population seems to have stayed down after being slaughtered,"],
    ["  ", "  and the ones who got up have largely dispersed through the countryside."],
    ["  ", "At least we won't get swarmed."]
], "Post Town": [
    ["> ", "We found a paladin inside the flame temple. His head had been cut off in twisted imitation of an elemental."],
    ["  ", "There was also a note staked into his chest. It simply reads, 'I warned you.'"],
    ["  ", "Akeem didn't look surprised to see that, which in turn didn't shock me."],
    ["  ", "I nearly started shouting at him to get the truth, but Fadia just said,"],
    ["  ", "  'we need to know,' in that gentle voice of hers. It worked."],
    ["", ""],
    ["> ", "It seems Akeem was the second member of his order sent to this nothing town."],
    ["  ", "The first, whom we just put down, came here chasing rumors of a vampire."],
    ["  ", "Seems to me he found one, but Akeem says even the most powerful bloodsuckers couldn't blight the land like this."],
    ["  ", "He's convinced something else is at work."],
    ["", ""],
    ["> ", "His order's library had a dusty, crumbling map of this region, which he studied before departing."],
    ["  ", "Reading it, he learned of a westerly feature called the 'Valley of Death.'"],
    ["  ", "He's going there next, purely on the basis of its name."],
    ["  ", "I suggested waiting for reinforcements from his order,"],
    ["  ", "  but he told me that no one else is likely to come for months."],
    ["", ""],
    ["> ", "Akeem also contends that whichever evil cursed this land may have weakened itself in doing so."],
    ["  ", "Every day we tarry affords it time to recover,"],
    ["  ", "  so he's off in a rush... and I suppose we're going with him."]
], "Ally": [
    ["> ", "We found a greater sphinx standing on cliff-side."],
    ["  ", "It was looking away from us, 'staring' down into a blighted gorge which we presume to be the Valley of Death."],
    ["  ", "We almost left the monster be before Layth decided to break off."],
    ["  ", "Ignoring my commands, she walked right up to the thing and started grooming it."],
    ["  ", "After a few seconds of getting licked, the elemental turned and gently tapped its neck stub against her."],
    ["  ", "Then it leapt off the cliff and glided down into the valley."],
    ["", ""],
    ["> ", "Fadia and I don't know what to make of that. Even Akeem says he's never seen the like."],
    ["  ", "Elemental guardians are never friendly. At best, they ignore you."],
    ["", ""],
    ["> ", "I wonder if we'll see it again."]
], "Valley": [
    ["> ", "The valley before us holds no structures aside from pyramids and hosts no life but scavengers."],
    ["  ", "This entire landscape is a massive, crumbling tomb."],
    ["  ", "The others almost seem excited to explore. I am the only sane one present."],
    ["", ""],
    ["> ", "We climbed a small hill to survey what lies before us. At its peak, we found a weathered stele."],
    ["  ", "Several words had long since chipped away, but the most important phrase endured:"],
    ["  ", "'In this accursed valley is inturned a lich. Turn back before death claims you.'"],
    ["  ", "We know now what awaits us; I cannot fathom how we will vanquish it."]
], "Lich": [
    ["> ", "We've reached the seat of this evil and will soon venture inside."],
    ["  ", "The ziggurat appears humble from without- smaller and cruder than the pyramids around it."],
    ["  ", "From its scale and placement at the valley's end, we believe it to be older than most of its neighbors."],
    ["", ""],
    ["> ", "Ancient glyphs mark the old tomb's lintel, still half-legible after two thousand years of abandonment."],
    ["  ", "I had thought myself a learned man when I lived among sailors, but Akeem is a true scholar."],
    ["  ", "He managed to translate what remains of the inscription. Its words both sickened and encouraged me."],
    ["", ""],
    ["> ", "I had assumed the lich was never destroyed because his obliteration was impossible,"],
    ["  ", "  but it seems he endures only because his captors wanted him to suffer."],
    ["  ", "He was an ancient lord whose peers hated him enough to make him an eternal prisoner."],
    ["  ", "Goddess willing, we will end his millennia of torment and stop the spread of his blight."],
    ["  ", "We can only hope his guards oblige us."]
], "Post Lich": [
    ["> ", "I'm not sure how, but we're all still alive. Akeem credits providence."],
    ["  ", "Fadia pointed out that the lich already appeared injured when we arrived;"],
    ["  ", "  some other enemy may have had a go at it at some point in the past century."],
    ["  ", "Regardless, we've accomplished slightly more than we'd set out to do on our descent."],
    ["", ""],
    ["> ", "Next to the lich's throne, we found a bag of silver coins. Modern quality of an unfamiliar mint."],
    ["  ", "No idea what the dead man planned to spend that on, but it looks like someone recently hired and payed him."],
    ["", ""],
    ["> ", "One side of each coin shows the image of a lone mountain by the sea."],
    ["  ", "There's a mountain just like that at the bay's south eastern coast."],
    ["  ", "It's the same one Fadia wanted to visit. Where her family-friend lives."],
    ["  ", "She hasn't mentioned that objective since we met Akeem. I'd almost forgotten it."],
    ["", ""],
    ["> ", "We'll need answers from her before this is done."],
    ["  ", "I'll force that conversation soon. I don't feel ready for it tonight."],
    ["", ""],
    ["> ", "Secrets aside, the question of how we cross the bay still remains."],
    ["  ", "Akeem's maps showed him a 'narrow' straight to our south. Only a few miles from beach to beach."],
    ["  ", "I'm confident I can build a raft fit to float that distance in calm weather."],
    ["  ", "Fadia claims she can hide us from predators. Akeem offered to pray the whole way."],
    ["", ""],
    ["> ", "I don't love our odds, but those are terrible regardless."],
    ["  ", "Onwards we go."]
], "Raft": [
    ["> ", "I finally confronted Fadia about her intentions in coming here."],
    ["  ", "She must have been waiting for me to say something,"],
    ["  ", "  because she just opened her hand and showed me another coin of the same make we found on the lich."],
    ["  ", "Hers is tarnished and a little more crude, but it depicts the same mountain."],
    ["", ""],
    ["> ", "Akeem and I had several questions after seeing that. Fadia claims not to know many answers."],
    ["  ", "Someone on that mountain has owed her family a favor for five generations."],
    ["  ", "She didn't know the immortal in question was a vampire when she set out,"],
    ["  ", "  but she's suspected it since Akeem explained his mission."],
    ["", ""],
    ["> ", "We didn't hear about this sooner because Fadia had worried we'd turn on her,"],
    ["  ", "  and we couldn't have reached the mountain before building our raft anyway."],
    ["  ", "She hopes she's proven her commitment to our cause by now."],
    ["", ""],
    ["> ", "Akeem was willing to let it drop if she told us what she wanted from the vampire."],
    ["  ", "She refused to answer, then swore on her own magic that she isn't seeking his help any more."],
    ["  ", "We're apparently just going to live with that for now."]
], "Dragon": [
    ["> ", "We were fools to venture so deeply into this marsh."],
    ["  ", "In her benevolence, the goddess granted us what I suspect will be our only warning."],
    ["  ", "We saw and felt the dragon's shadow cross over our bodies before we heard the beating of its wings."],
    ["  ", "The great beast must have glided towards us silently, keeping to our blind spot until it rose from its dive."],
    ["", ""],
    ["  ", "Fadia thinks the creature was merely curious. Akeem agreed with me that its coming was a message."],
    ["  ", "Both acknowledged that staying here would be the death of us. We're turning back."]
], "Finale": [
    ["> ", "We see a manor at the mountaintop. Our final objective."],
    ["  ", "With the vampire's lair in sight, Akeem decided to press the issue of Fadia's purpose in coming here."],
    ["  ", "To my surprise, she actually confessed it."],
    ["  ", "Fadia came to this land in the hopes of obtaining immortality. No other reason."],
    ["", ""],
    ["> ", "She repeated her claim that she hadn't known her family's 'man of the mountain' was actually a vampire..."],
    ["  ", "But come on. She's not an idiot. The thought must have crossed her mind."],
    ["  ", "She won't outright confess to a paladin that she'd planned to sacrifice her own soul for eternal life,"],
    ["  ", "  but he and I aren't idiots either."],
    ["", ""],
    ["> ", "I'm not sure how much trust I would extend if Fadia and I were here alone."],
    ["  ", "We've bled together, yes, but this is no minor hurdle."],
    ["  ", "Akeem though, was just quiet for a few seconds before saying,"],
    ["  ", "  'Heaven brought us together for this purpose. I will keep faith if you do likewise, sister.'"],
    ["", ""],
    ["> ", "I suppose that's it."],
    ["  ", "We'll find out soon how true she really is."]
], "Post Finale": [
    ["> ", "Vengeance is delivered."],
    ["  ", "Hopefully the people of that rotted town will find their way to restful slumber."],
    ["  ", "I'm not going back to check."],
    ["", ""],
    ["> ", "In marginally happier news, we've discovered that the vampire recorded his thoughts in journals like I do."],
    ["  ", "His entires go back centuries, though it's clear he was often unsure of actual dates- even to the decade."],
    ["  ", "I skipped to the final sections to see if I could piece together what happened between him and that town."],
    ["", ""],
    ["> ", "From what I could gather, he'd been preying on the locals for a long time."],
    ["  ", "Their ancestors used to offer him sacrifices in exchange for protection."],
    ["  ", "That formalized association stopped a generation ago,"],
    ["  ", "  but their unholy equilibrium sustained itself until the first paladin from"],
    ["  ", "  Akeem's order arrived to complete the town's rebellion against its former master."],
    ["", ""],
    ["> ", "Preferring to starve on his own terms,"],
    ["  ", "  the vampire struck a deal with an evil more ancient than himself (his own words)."],
    ["  ", "The lich traded a 'seed of rot' for assistance in dispelling the curse which had confined him to his crypt."],
    ["  ", "The vampire believed no such curse still existed, if it ever had,"],
    ["  ", "  so when the lich delivered on his promise, he tried to pay his debt in coin instead."],
    ["", ""],
    ["> ", "The two blackhearts came to blows over that disagreement,"],
    ["  ", "  but the vampire ultimately escaped with his newly minted 'paladin of rot.'"],
    ["  ", "We know the rest of their stories..."],
    ["", ""],
    ["> ", "Akeem thinks he knows an overland route to the south that should eventually bring us to another settlement."],
    ["  ", "It'll be a long trek, but at least I have decent company."],
    ["  ", "Before we get there, I should ask whether his order has any need for another ship captain."],
    ["  ", "This hero business suits me."]
]}