

scenes = {"Escape": [
    ["> ", "This journal was the first object I ever stole."],
    ["  ", "I snatched it from our warden's desk before helping myself to his weapons."],
    ["  ", "Laura called me foolish for searching his shelves for a quill but changed her tune when I found his core stash."],
    ["  ", "Finally: proof that my hobbies are useful."],
    ["", ""],
    ["> ", "We have another's day's march before we enter the fjord."],
    ["  ", "Laura wants to head East from there- into the glacier."],
    ["  ", "Of this region's three titans, the worm should prove easiest to hunt."],
    ["", ""],
    [">  ", "Whichever route we follow, we have maybe ten days to return here."],
    ["  ", "If we aren't prepared to strike within the next two weeks... Willem dies alone."]
], "Threshold": [
    ["> ", "Laura says these woods haven't been settled since before our language first developed."],
    ["  ", "Judging from the ruins we've spotted, I believe her."],
    ["", ""],
    ["> ", "Nobody lives here now, at any rate. The wild's gentlest regions serve only as hunting grounds."],
    ["  ", "It isn't safe to linger even at the margins; no one sane delves deeper."],
    ["  ", "On that subject, Laura says she's looking forward to seeing her first intact flame elemental."],
    ["  ", "I'm not."]
], "Moose": [
    ["> ", "We saw a bull moose swimming across the fjord and stopped for a minute to observe its progress."],
    ["  ", "I was making some comment about the weather when our creature disappeared."],
    ["  ", "I saw the moment it vanished clearly enough to tell it wasn't diving. It simply fell beneath the surface."],
    ["  ", "Like it was pulled."],
    ["  ", "There weren't any sings of struggle, though. No thrashing limbs beneath the surface."],
    ["  ", "Whatever gabbed that beast either killed it instantly or dragged it deep."],
    ["", ""],
    ["> ", "If we'd had any intentions of making a raft..."]
], "Worm": [
    ["> ", "Around every other corner we find an elemental placidly standing in the paths."],
    ["  ", "Some are even frozen inside the walls. They seem at peace, or at least their postures look relaxed."],
    ["  ", "It's certainly frigid enough that they've got nothing to complain about."],
    ["", ""],
    ["> ", "The air here gets so cold that I have a blanket of frost forming on my beard."],
    ["  ", "That means we're close to our quarry, per Laura."],
    ["  ", "Right after she said that, I told her that her eyes look beautiful with ice clinging to her lashes."],
    ["  ", "She ordered me to focus. :("],
    ["", ""],
    ["> ", "We just heard a rumble from up ahead, so I suppose I'm done writing for now."],
    ["  ", "Gods willing, this won't be my final entry."],
], "Post Worm": [
    ["> ", "The ice shard nearly gave me frostbite."],
    ["  ", "I only handled for a few seconds while wearing gloves."],
    ["  ", "The power concentrated in this little thing..."],
    ["", ""],
    ["> ", "Before we ventured north, I doubted Laura's plan."],
    ["  ", "After holding the thing myself, I could feel she was right. This can work."],
], "Vines": [
    ["> ", "Laura saved my life again."],
    ["  ", "We found a narrow stream on our way uphill. Its water smelled sour, so we crossed with care but otherwise thought little of it."],
    ["  ", "A minute later, quiet voices began singing to me of rest and comfort."],
    ["  ", "I said we should investigate, but Laura couldn't hear what I had heard. That only made me more curious."],
    ["  ", "The the poor woman all-but-dragged me back the way we'd come."],
    ["  ", "I protested every step, but as soon as we crossed that stream again, my wits returned."],
    ["", ""],
    ["> ", "Laura isn't certain what ensnared me, but she shared a guess."],
    ["  ", "There's a plant on the southern continent called an angler vine. It hunts by luring prey into an open stomach buried in the ground."],
    ["  ", "It isn't supposed to grow this far north. Our winters should have killed it."],
    ["  ", "I wonder if the ancients changed it somehow. Maybe it's been growing here since their empire collapsed."],
    ["", ""],
    ["> ", "Regardless, today reminded me that despite our prowess, ambitions, and achievements,"],
    ["  ", " there are still places in this world better left alone."]
], "Giant": [
    ["> ", "We found the giant's tracks atop a bed of moss."],
    ["  ", "There's no other explanation for that confused mess of scorch marks, frostbite, decay, and physical damage."],
    ["  ", "We're close to our target now."],
    ["  ", "I should feel anticipation, but I'm mostly nostalgic."],
    ["", ""],
    ["> ", "I remember hearing ghost stories about this titan as a child."],
    ["  ", "Every telling differs, but most hold that it's been here longer than the other beasts."],
    ["  ", "Some say it was once an ancient sorcerer- denied the peace of death for his sins and cursed to roam the earth."],
    ["  ", "Others describe it as one of their escaped experiments."],
    ["  ", "Almost all accounts agree that it often travels south to eat naughty children who don't listen to their mothers."],
    ["  ", "I'm sure my sources were reliable."],
    ["", ""],
    ["> ", "We'll soon find out how many of its legends are true."],
    ["  ", "If half of them are, this will be an interesting fight."]
], "Post Giant": [
    ["> ", "One more monster in the dirt. Laura and I have a knack for this."],
    ["", ""],
    ["> ", "The roughest moment of the fight came at the end."],
    ["  ", "It started yelling at us, and for a few seconds I believed it was speaking."],
    ["  ", "That would have made things difficult."],
    ["", ""],
    ["> ", "I can kill bandits and the duke's soldiers when they beg for mercy, but only because they start every fight."],
    ["  ", "We hunted this creature."],
    ["  ", "If it'd started pleading for life, I might have abandoned our plan then and there."],
    ["  ", "I still feel sullied after butchering something with such a human voice."],
    ["  ", "At least its face doesn't look like ours."],
], "Strider": [
    ["> ", "The volcano started bellowing ash as we neared its summit. With no time to retreat, we sheltered inside a cave."],
    ["  ", "I covered our bodies with my cloak, then Laura brought my face close to hers and formed a wreath around our heads."],
    ["  ", "Her magic kept the smoke at bay so we could breathe clean air. We saw each other just as clearly. Only an inch apart."],
    ["  ", "I thought about kissing her for every second of that embrace."],
    ["  ", "She gave me quite a shock by doing it first."],
    ["  ", "The feeling of her lips against my own was everything I'd imagined."],
    ["  ", "Without thinking, I tightened my grip around her back and pulled her into me."],
    ["  ", "That must have been too distracting, because her spell failed and we both inhaled a lungful of smoke."],
    ["", ""],
    ["> ", "It's just as well. Now is not the time for dalliance."],
    ["  ", "As soon as all three shards are in our hands, we can return south."],
    ["  ", "If we survive what comes after, there will be much to discuss."]
], "Post Strider": [
    ["> ", "We have the flame shard."],
    ["  ", "It's energetic in a way I can't fully describe."],
    ["  ", "Just looking at it made me feel as though a kiln was blazing behind my eyes."],
    ["  ", "It's former host barely touched this wellspring."],
    ["  ", "We'll put that magic to better use."],
], "Breakout": [
    ["> ", "We've returned to our old fort and plan to hide nearby until dusk."],
    ["  ", "The duke has reinforced this post significantly. Getting in would prove far more challenging than our escape."],
    ["  ", "Good thing we don't need to bother."],
], "Post Breakout": [
    ["> ", "There's no going back."],
    ["  ", "Laura's ritual barely left us enough time to slip past the fort before"],
    ["", ""],
    ["  ", "Gods, I didn't expect so much power. That flash turned night to day."],
    ["  ", "The magic was thick enough that even I could feel it pressing on my skin."],
    ["  ", "Elementals were already forming by the time we got out. Every last one of them looked angry."],
    ["", ""],
    ["> ", "Laura says that patch of ground will remain infused for several days."],
    ["  ", "I can't see it can ever returning to what it was."],
    ["  ", "Regardless, the fort has fallen."],
    ["  ", "We saw disorganized survivors making their retreat along the high road."],
    ["  ", "It wasn't clear who held command. They might have been deserters."],
    ["  ", "Clever men, if so, but anyone who shelters at the port will curse his luck for it soon."],
    ["", ""],
    ["  ", "Before we strike there, we need to press into the eastern hills."],
    ["  ", "Willem awaits."]
], "Strange Fruit": [
    ["> ", "We found something odd on the beach- an iron sculpture in the shape of a fantastical fruit."],
    ["  ", "It somewhat looks like armored potato with a shock of leaves protruding from its top."],
    ["  ", "Laura said it reminds her of a pinecone."],
    ["", ""],
    ["> ", "Given its density, I'm not sure how it washed up here instead of sinking."],
    ["  ", "Perhaps it was filled with hot air."],
    ["", ""],
    ["> ", "Laura suggested throwing it back into the water to see how it fares, but I decided to hide it a ways inland."],
    ["  ", "I'll return for this later if I can find my way back."],
    ["  ", "Watching it brought me comfort."]
], "Camp": [
    ["> ", "Willem's health has improved. He can walk again."],
    ["  ", "We saw him taking a stroll around the camp with a guard holding each arm."],
    ["  ", "They never let him get within twelve paces of anyone carrying a bow or banner."],
    ["  ", "We'll need to craft what he needs and get it into his hands before the killing starts."],
    ["  ", "As much as he loves watching his juniors work, I know he hates feeling left out."],
    ["", ""],
    ["> ", "Laura said she's almost convinced we should just strike now, but we agreed to follow the plan."],
    ["  ", "Let the duke's two-faced pet think we've brought his ransom."],
    ["  ", "As soon as Willem's in front of us, the highwayman dies."],
    ["  ", "After that, we'll need to run."]
], "Post Camp": [
    ["> ", "It worked! We're reunited with our old mentor, and he's still as spry as ever."],
    ["  ", "Willem carries himself as if this whole ordeal was a minor inconvenience."],
    ["  ", "The man barely seems to mind that his cousin tried to have him killed."],
    ["  ", "He's far more upset about his lands and horses being seized."],
    ["  ", "We'll get it all back soon."],
    ["", ""],
    ["> ", "As for the bandits, they haven't pursued us."],
    ["  ", "Their best men were gathered in that tent for the handoff."],
    ["  ", "What's left doesn't want to give chase, especially with no leader to urge them."],
    ["", ""],
    ["> ", "I doubt we've expunged their ilk from the region entirely, but they won't cling to these hills as firmly as they used to."],
    ["  ", "It felt good to finally deal with them. Like working out a splinter."],
    ["  ", "Now we just have one more irritant to remove."],
    ["  ", "I wonder if the duke is expecting us yet. I hope he hasn't fled."]
], "Finale": [
    ["> ", "The tiny port which shares Willem's surname finally lies before us."],
    ["  ", "Its new master is still in residence. We saw him visit the docks, struggling to restore order amidst the chaos we've already sown."],
    ["  ", "He won't have that problem much longer."],
], "Post Finale": [
    ["> ", "The usurper is dead. His southern troops have fled across the river."],
    ["  ", "Judging by the course of their dust trail, most chose to bypass our nearest city to seek refuge further south."],
    ["  ", "Perhaps they're going all the way home, or maybe they're afraid we'll bring disaster on their heads a third time if they stop too close."],
    ["  ", "We'd never afflict our own people in that way, but no one besides the three of us yet knows how far we're willing to go."],
    ["  ", "That point need to be clarified quickly, lest we appear too wild to be left alive."],
    ["", ""],
    ["> ", "To this end, Willem has drafted a letter to His Majesty. We intend to convey it southward through parties sympathetic to our cause."],
    ["  ", "The missive affirms our enduring loyalty to the crown while also declaring that one elemental shard remains in our possession."],
    ["  ", "Our phrasing implies that we want to surrender this final weapon in exchange for clemency and re-legitimization."],
    ["  ", "We have also awarded ourselves due credit for the disruption of banditry and laid all blame for its recent rise with the upstart Duke."],
    ["", ""],
    ["> ", "Time will tell whether our gambit profits us."],
    ["  ", "If our king refuses to parley, then we can always flee back north."]
]}